- [错误处理与调试](#错误处理与调试)
  - [错误处理](#错误处理)
    - [try/catch 语句](#trycatch-语句)
    - [抛出错误](#抛出错误)

## 错误处理与调试

### 错误处理

#### try/catch 语句

ECMA-262 第 3 版新增了 try/catch 语句，作为在 JavaScript 中处理异常的一种方式。基本的语法如下所示，跟 Java 中的 try/catch 语句一样：

```js
try {
  // 可能出错的代码
} catch (error) {
  // 出错时要做什么
}
```

1. `finally` 子句
   如果 try 块中的代码运行完，则接着执行 finally 块中的代码。如果出错并执行 catch 块中的代码，则 finally 块中的代码仍执行。try 或 catch 块无法阻止 finally 块执行，包括 return 语句。

```js
function testFinally() {
  try {
    console.log('2');
    return 2;
  } catch (error) {
    console.log('1');
    return 1;
  } finally {
    console.log('0');
    return 0;
  }
}

let res = testFinally(); // 0
```

> 只要代码中包含了 finally 子句，try 块或 catch 块中的 return 语句就会被忽
> 略，理解这一点很重要。在使用 finally 时一定要仔细确认代码的行为。

#### 抛出错误

与 try/catch 语句对应的一个机制是 throw 操作符，用于在任何时候抛出自定义错误。throw 操作符必须有一个值，但值的类型不限。

自定义错误类型：

```js
class CustomError extends Error {
  constructor(message) {
    super(message);
    this.name = 'CustomError';
    this.message = message;
  }
}
throw new CustomError('My message');
```

## 小结

对于今天复杂的 Web 应用程序而言，JavaScript 中的错误处理十分重要。未能预测什么时候会发生错误以及如何从错误中恢复，会导致糟糕的用户体验，甚至造成用户流失。大多数浏览器默认不向用户报告 JavaScript 错误，因此在开发和调试时需要自己实现错误报告。不过在生产环境中，不应该以这种方式报告错误。
下列方法可用于阻止浏览器对 JavaScript 错误作出反应。

- 使用 try/catch 语句，可以通过更合适的方式对错误做出处理，避免浏览器处理。
- 定义 window.onerror 事件处理程序，所有没有通过 try/catch 处理的错误都会被该事件处理程序接收到（仅限 IE、Firefox 和 Chrome）。

开发 Web 应用程序时，应该认真考虑可能发生的错误，以及如何处理这些错误。

- 首先，应该分清哪些算重大错误，哪些不算重大错误。
- 然后，要通过分析代码预测很可能发生哪些错误。由于以下因素，JavaScript 中经常出现错误：
- 类型转换；
- 数据类型检测不足；
- 向服务器发送错误数据或从服务器接收到错误数据。

IE、Firefox、Chrome、Opera 和 Safari 都有 JavaScript 调试器，有的内置在浏览器中，有的是作为扩展，需另行下载。所有调试器都能够设置断点、控制代码执行和在运行时检查变量值。
